### GET ALL BLOGS
GET http://localhost:3003/api/blogs

### POST A BLOG
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2M2RkOWQ0NWIwMDJkMzNmOWMxOTlkOWUiLCJpYXQiOjE2NzU0NzIxNTF9.FaTX2RRvjxI_zoEAFV3fURKOQFyljuUTX0XzRxCjJBQ

{
  "title": "IS THIS THE LAST TEST FROM PART 4?",
  "author": "SuperAdminJJ",
  "url": "HELLO WORLD"
}

### DELETE A BLOG
DELETE http://localhost:3003/api/blogs/63e28af4cee04b4db2416064
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2M2RkOWQ0NWIwMDJkMzNmOWMxOTlkOWUiLCJpYXQiOjE2NzU0NzIxNTF9.FaTX2RRvjxI_zoEAFV3fURKOQFyljuUTX0XzRxCjJBQ

### EDIT A BLOG
PUT http://localhost:3003/api/blogs/63e28a730896d89272163971
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2M2RkOWQ0NWIwMDJkMzNmOWMxOTlkOWUiLCJpYXQiOjE2NzU0NzIxNTF9.FaTX2RRvjxI_zoEAFV3fURKOQFyljuUTX0XzRxCjJBQ

{
  "title": "THIS BLOG IS GOING TO BE DELETED",
  "author": "JJBANDANA",
  "url": "Updating this blog"
}
